### ISSUE TITLE
新闻客户端获取本地web服务方面的代码

### ISSUE THREAD

**Issue by Chankit8** [liaozhoubei/NetNewsDemo#1]
你好，可以分享新闻客户端获取本地web服务方面的代码参考一下吗

**Comment by liaozhoubei** [comment]
> 你好，可以分享新闻客户端获取本地web服务方面的代码参考一下吗
抱歉，好久没看git了，这么晚了，估计也不需要，但是还是把本地web的代码给你吧，需要在百度网盘下载。

https://pan.baidu.com/s/1o8iZukU
